name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Criar .env
      run: |
        echo "BASE_URL_REST=${{ secrets.BASE_URL_REST }}" >> .env        

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    # Testes REST (controller)
    - name: Rodar os testes de API REST via controller
      run: npm run test-rest-controller

    # Testes REST (external)
    - name: Subir a API REST
      run: npm run start-rest &
    - name: Esperar a API REST estar Funcionando
      run: sleep 5
    - name: Rodar os testes de API REST via HTTP
      run: npm run test-rest-external